[ADD] openacademy: Add new module to manage an academy
jjbenavaz/openacademy-repo pull request #1
Opened 2022-05-18 16:21 UTC by jjbenavaz

- Added a new module
- Added basic views (form, tree and search views)

2022-05-18 16:25 UTC, jjbenavaz commented
Hi @edy1192 , can you please check this out?

2022-05-18 17:09 UTC, edy1192 requested changes

2022-05-18 17:09 UTC, edy1192 commented on openacademy/__init__.py
> +# -*- coding: utf-8 -*-
Please remove all the `# -*- coding: utf-8 -*-` in the files. This sentences is not necessary anymore, actually there's a lint for that.

You could do it with this command:

`find . -name "*.py" -type f -exec sed -i '/^#.*coding/d; /^# Part of Odoo/d; /./,$!d' '{}' \;`

2022-05-18 17:09 UTC, edy1192 commented on openacademy/__manifest__.py
> +
Please remove all the blank lines between dictionary keys, there's not necessary.
You could see [this](https://github.com/odoo/odoo/blob/15.0/addons/account/__manifest__.py) to take as an example.

2022-05-18 17:09 UTC, edy1192 commented on openacademy/__manifest__.py
> +
Change the summary of the module. Add the module's purpose like: "Manage academy training."

2022-05-18 17:09 UTC, edy1192 commented on openacademy/__manifest__.py
> +        Long description of module's purpose
Same as above.

2022-05-18 17:09 UTC, edy1192 commented on openacademy/__manifest__.py
> +        'views/templates.xml',
Views should be named and grouped by model name, e.g. openacademy_course_view.xml. For more info, check [the guidelines](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#15file-naming)

2022-05-18 17:09 UTC, edy1192 commented on openacademy/__manifest__.py
> +        'demo/demo.xml',
Same as above. 
```suggestion
        'demo/open_academy_course_demo.xml',
```

2022-05-18 17:09 UTC, edy1192 commented on openacademy/controllers/controllers.py
> +# -*- coding: utf-8 -*-
Avoid adding commented code. If this code is not used then better not to add the file for now.

2022-05-18 17:09 UTC, edy1192 commented on openacademy/models/__init__.py
> +from . import models
Please name files according to models: 
```suggestion
from . import openacademy_course
```

2022-05-18 17:09 UTC, edy1192 commented on openacademy/models/models.py
> +    _description = 'Model to store course'
`_name` and `_description` are attributes of the model, should be [together](https://github.com/odoo/odoo/blob/15.0/addons/account/models/account_account_tag.py#L7-L8). Please organize them.
```suggestion
    _name = 'openacademy.course'
    _description = 'Model to store course'
    
     name = fields.Char(string="Title", required=True)
    description = fields.Text()
```

2022-05-18 17:09 UTC, edy1192 commented on openacademy/views/templates.xml
> +<!--
Delete this file if you are not using it.

2022-05-18 17:09 UTC, edy1192 commented on openacademy/views/views.xml
> +            <tree string="Course Tree">
String is deprecated in tree views, please remove it:

```suggestion
            <tree>
```
You could see the [guidelines](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#23views)

2022-05-18 17:09 UTC, edy1192 commented on openacademy/views/views.xml
> +-->
Please delete commented code.

2022-05-18 17:09 UTC, edy1192 commented on openacademy/views/views.xml
> +    <record model="ir.actions.server" id="openacademy.action_server">
Same as above.

2022-05-18 17:09 UTC, edy1192 commented on openacademy/models/models.py
> +from odoo import models, fields, api
Please avoid import things that you don't use, like `api`. 

I know you'll use it later, but don't import it for now.

2022-05-18 17:11 UTC, edy1192 commented
Please delete the manifest.py file and squash all commits into only one.

If you have doubts with squash, we can see it.

2022-05-18 19:22 UTC, jjbenavaz commented on openacademy/__manifest__.py
> +        'views/templates.xml',
So, should I change the name of the views.xml to openacademy_course.xml and then also update __manifest.py__ to point to the file with the new name?

2022-05-18 19:25 UTC, edy1192 commented on openacademy/__manifest__.py
> +        'views/templates.xml',
Yes please. You should name the file `openacademy_course_views.xml`

2022-05-18 22:32 UTC, edy1192 requested changes

2022-05-18 22:32 UTC, edy1192 commented on openacademy/models/__init__.py
> +from . import models
Pending https://github.com/jjbenavaz/openacademy-repo/pull/1#discussion_r876128740

Please rename the file `models.py `to `openacademy_course.py ` like you did with the views file.

Guidelines: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#15file-naming

2022-05-18 22:32 UTC, edy1192 commented on openacademy/__manifest__.py
> +        'demo/demo.xml',
This change is pending. 

Please rename demo file and change it in the manifest.

2022-05-18 22:32 UTC, edy1192 commented on openacademy/__init__.py
Avoid empty lines please.

2022-05-18 22:32 UTC, edy1192 commented on openacademy/controllers/__init__.py
Avoid empty lines please.

2022-05-18 22:32 UTC, edy1192 commented on openacademy/models/models.py
> +class Session(models.Model):
Please move this model to new file `openacademy_session.py` and add it to the init file.

2022-05-18 22:32 UTC, edy1192 commented on openacademy/models/models.py
Pending https://github.com/jjbenavaz/openacademy-repo/pull/1#discussion_r876131522

2022-05-19 15:12 UTC, jjbenavaz commented on openacademy/models/models.py
done

2022-05-19 15:28 UTC, jjbenavaz commented on openacademy/__manifest__.py
> +        'demo/demo.xml',
done

2022-05-19 16:09 UTC, jjbenavaz commented on openacademy/controllers/controllers.py
> +# -*- coding: utf-8 -*-
done, I removed controllers.py and also __init__.py from controllers/, since it basically does nothing w/o controllers.py

2022-05-19 16:10 UTC, jjbenavaz commented on openacademy/models/__init__.py
> +from . import models
done

2022-05-19 17:17 UTC, edy1192 requested changes
@jjbenavaz please remove all the binary files - Those came from the pycache directory. You could add that directory to .gitignore 
 file. Like this https://github.com/Vauxoo/addons-vauxoo/blob/14.0/.gitignore#L2

2022-05-19 17:17 UTC, edy1192 commented on openacademy/models/__init__.py
> +from . import openacademy_course, openacademy_session
Please one line for import like this 

https://github.com/Vauxoo/addons-vauxoo/blob/14.0/account_chatter/models/__init__.py#L4-L6

2022-05-19 23:46 UTC, edy1192 approved these changes

2022-05-19 23:50 UTC, merged